# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitFire < Formula
  desc "Emergency git backup - commit and push all repos when disaster strikes"
  homepage "https://github.com/git-fire/git-fire"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-fire/git-fire/releases/download/v0.3.0/git-fire_0.3.0_darwin_amd64.tar.gz"
      sha256 "8a1030b0ea4974131f0b1270bcab78054d945b256b89a9a595e60e23ac8cc2ac"

      define_method(:install) do
        bin.install "git-fire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-fire/git-fire/releases/download/v0.3.0/git-fire_0.3.0_darwin_arm64.tar.gz"
      sha256 "4abba2bea91161e72fd7ede15c0fed104c7fbb87b39163b0c6634baa015d7db5"

      define_method(:install) do
        bin.install "git-fire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-fire/releases/download/v0.3.0/git-fire_0.3.0_linux_amd64.tar.gz"
      sha256 "454456d3b991c3a134da3be7f34fd5b60b5cc49da398214851ac752229763e33"
      define_method(:install) do
        bin.install "git-fire"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-fire/releases/download/v0.3.0/git-fire_0.3.0_linux_armv6.tar.gz"
      sha256 "fbbb97b759369b87394566c257de83fc5de93cf080c144822630edd9914449fe"
      define_method(:install) do
        bin.install "git-fire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-fire/releases/download/v0.3.0/git-fire_0.3.0_linux_arm64.tar.gz"
      sha256 "921801b29228450a7f77d259f5d2ef533cc79ed04bbc1729449ade6829ab53e3"
      define_method(:install) do
        bin.install "git-fire"
      end
    end
  end

  test do
    system "#{bin}/git-fire", "--version"
  end
end
