# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitFire < Formula
  desc "Emergency git backup - commit and push all repos when disaster strikes"
  homepage "https://github.com/git-fire/git-fire"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-fire/git-fire/releases/download/v0.2.0/git-fire_0.2.0_darwin_amd64.tar.gz"
      sha256 "9d5d700ba7a1273ff4f9a28f75b48348f1a1ba1a54871fa2840f5328830424c5"

      define_method(:install) do
        bin.install "git-fire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-fire/git-fire/releases/download/v0.2.0/git-fire_0.2.0_darwin_arm64.tar.gz"
      sha256 "6c8a147c221bdff1e92e7f1e3f6e2ffabfc5326bc0917841a7babe1434045f3b"

      define_method(:install) do
        bin.install "git-fire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-fire/releases/download/v0.2.0/git-fire_0.2.0_linux_amd64.tar.gz"
      sha256 "4cba1f188d5addf5f7ea602fe9f17a8576b1a50154cc3e45be5f178eb79b6b47"
      define_method(:install) do
        bin.install "git-fire"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-fire/releases/download/v0.2.0/git-fire_0.2.0_linux_armv6.tar.gz"
      sha256 "bed27d64ec9c43472ed2347f8be8507f473fe53bd3c688709b7ec6e82fee34c2"
      define_method(:install) do
        bin.install "git-fire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-fire/releases/download/v0.2.0/git-fire_0.2.0_linux_arm64.tar.gz"
      sha256 "201994331be09711ad6f4c4fa46e330cf1784d76fdcfb9db64cf6b3be120113a"
      define_method(:install) do
        bin.install "git-fire"
      end
    end
  end

  test do
    system "#{bin}/git-fire", "--version"
  end
end
