# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitRain < Formula
  desc "Sync local git repositories from their remotes — the reverse of git-fire"
  homepage "https://github.com/git-fire/git-rain"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-fire/git-rain/releases/download/v0.1.0/git-rain_0.1.0_darwin_amd64.tar.gz"
      sha256 "062e92e586cb2294be69372b0327fbf8251a314676594b11cf7b4521f7de198c"

      define_method(:install) do
        bin.install "git-rain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/git-fire/git-rain/releases/download/v0.1.0/git-rain_0.1.0_darwin_arm64.tar.gz"
      sha256 "d8968d5fb7fa7daf6a51b9bdf10e65efe4d09fbf48415cd8063ef4ca4bc5ea8d"

      define_method(:install) do
        bin.install "git-rain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-rain/releases/download/v0.1.0/git-rain_0.1.0_linux_amd64.tar.gz"
      sha256 "488320a0c8b3ab420a7e62e6bb36280f179aa77143814a25d6750927c57ef5b8"
      define_method(:install) do
        bin.install "git-rain"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-rain/releases/download/v0.1.0/git-rain_0.1.0_linux_armv6.tar.gz"
      sha256 "5829928416db1e61f403b2f86254d51ceac7709822120cc589a1958bf77fe97b"
      define_method(:install) do
        bin.install "git-rain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/git-fire/git-rain/releases/download/v0.1.0/git-rain_0.1.0_linux_arm64.tar.gz"
      sha256 "52c624e7823430e6a1f267b1306b597d26181cd0c3d98f2cfeac50d7470eb4fd"
      define_method(:install) do
        bin.install "git-rain"
      end
    end
  end

  test do
    system "#{bin}/git-rain", "--version"
  end
end
